name: Code Analysis

on:
  workflow_call:

  workflow_dispatch:

  pull_request:
    branches:
      - main
      - master
    # Optional: Pfadfilter, um den Workflow nur bei Änderungen an Kotlin-Dateien auszuführen
    # paths:
    #   - '**.kt'
    #   - '**.kts'

jobs:
  ktlint: # Job-ID für Ktlint
    name: Ktlint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

  detekt: # Job-ID für Detekt
    name: Detekt Analysis
    runs-on: ubuntu-latest
    needs: ktlint # <--- HIER WIRD DIE ABHÄNGIGKEIT DEFINIERT
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"    # Übliche Java-Version für moderne Android-Projekte

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # Kümmert sich um Caching etc.

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt
