name: SonarQube Pull Request Analysis

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Wichtig für die korrekte Analyse des "New Code"

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Build, generate JaCoCo and Lint reports
#        run: ./gradlew app:lintDebug koverXmlReport  --stacktrace

      - name: SonarQube Analysis 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PR_KEY: ${{ github.event.pull_request.number }}
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
          PR_BASE: ${{ github.event.pull_request.base.ref }}
          PR_REPO: ${{ github.repository }}
          # SONAR_HOST_URL wird aus build.gradle.kts verwendet, falls dort konfiguriert,
          # oder Sie können es hier explizit setzen, wenn nötig:
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew sonar --stacktrace \
            -Dsonar.pullrequest.key=$PR_KEY \
            -Dsonar.pullrequest.branch=$PR_BRANCH \
            -Dsonar.pullrequest.base=$PR_BASE \
            -Dsonar.pullrequest.github.repository=$PR_REPO \
            -Dsonar.pullrequest.provider=github
